# Generated by Django 4.2.30 on 2026-07-06 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(choices=[('hospitality', 'Hospitality & Tourism'), ('banking', 'Banking & Finance'), ('accounting', 'Accounting & Audit'), ('marketing', 'Marketing'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('construction', 'Construction & Real Estate'), ('sales', 'Sales'), ('student', 'Student'), ('business_owner', 'Small Business Owner'), ('other', 'Other')], default='other', max_length=30)),
                ('district', models.CharField(blank=True, help_text='e.g. George Town, West Bay, Bodden Town', max_length=100)),
                ('learning_goal', models.CharField(blank=True, max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
