# Generated by Django 4.2.30 on 2026-07-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_id_document',
            field=models.ImageField(blank=True, help_text='Photo of a valid student ID, uploaded by the user to request the student discount.', null=True, upload_to='student_ids/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_status',
            field=models.CharField(choices=[('none', 'Not a student'), ('pending', 'Verification pending'), ('approved', 'Verified student'), ('rejected', 'Verification rejected')], default='none', max_length=10),
        ),
    ]
