# Generated by Django 4.2.30 on 2026-07-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_price_cents',
            field=models.PositiveIntegerField(blank=True, help_text='Optional discounted price (in cents) for verified students. Leave blank for no student discount.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='track',
            field=models.CharField(choices=[('general', 'General — everyone'), ('hospitality', 'Hospitality & Tourism'), ('banking', 'Banking & Finance'), ('accounting', 'Accounting & Audit'), ('marketing', 'Marketing'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('construction', 'Construction & Real Estate'), ('sales', 'Sales'), ('student', 'Students'), ('business_owner', 'Small Business Owners')], default='general', help_text='Which career track this course belongs to. Learners see courses matching their occupation first.', max_length=30),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional illustration shown at the top of the lesson.', null=True, upload_to='lessons/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='instructions',
            field=models.TextField(blank=True, help_text='Optional step-by-step instructions shown in a highlighted box (HTML or plain text).'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_cents',
            field=models.PositiveIntegerField(default=10000, help_text='Price in US cents, e.g. 10000 = $100.'),
        ),
    ]
