# Generated by Django 4.2.30 on 2026-07-07 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_course_student_price_cents_course_track_lesson_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('icon', models.CharField(default='school', help_text='Material Symbols icon name', max_length=50)),
                ('audience', models.CharField(choices=[('general', 'General — everyone'), ('hospitality', 'Hospitality & Tourism'), ('banking', 'Banking & Finance'), ('accounting', 'Accounting & Audit'), ('marketing', 'Marketing'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('construction', 'Construction & Real Estate'), ('sales', 'Sales'), ('student', 'Students'), ('business_owner', 'Small Business Owners')], default='general', help_text='Learners whose occupation matches see this track recommended first.', max_length=30)),
                ('price_cents', models.PositiveIntegerField(default=10000, help_text='Price in US cents, e.g. 10000 = $100.')),
                ('student_price_cents', models.PositiveIntegerField(blank=True, help_text='Optional discounted price (in cents) for verified students. Leave blank for no student discount.', null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order — the General track is usually first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='price_cents',
        ),
        migrations.RemoveField(
            model_name='course',
            name='student_price_cents',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.track'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='track',
        ),
        migrations.AddField(
            model_name='course',
            name='track',
            field=models.ForeignKey(blank=True, help_text='The track this course belongs to. Buying the track unlocks all of its courses.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.track'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'track')},
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
    ]
